version: '3'
services:

  watchtower:
    #image: v2tec/watchtower
    image: erseco/watchtower:hangouts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /home/ubuntu/.docker/config.json:/config.json
    #interval to 120s rather than the default 5 minutes.
    command: --interval 120 --cleanup --debug
    restart: unless-stopped
    networks:
      - traefik_default
    environment:
      REPO_USER: ${REPO_USER}
      REPO_PASS: ${REPO_PASS}
      # WATCHTOWER_NOTIFICATIONS: email
      # WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
      # WATCHTOWER_NOTIFICATION_EMAIL_TO: ${WATCHTOWER_NOTIFICATION_EMAIL_TO}
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER}
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT}
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
      # WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}
      WATCHTOWER_NOTIFICATIONS: hangouts
      WATCHTOWER_NOTIFICATION_HANGOUTS_CHAT_WEBHOOK_URL: ${WATCHTOWER_NOTIFICATION_HANGOUTS_CHAT_WEBHOOK_URL}

networks:
  traefik_default:
    external:
      name: traefik_default
