version: '3'
services:

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /home/ubuntu/.docker/config.json:/config.json
    #interval to 120s rather than the default 5 minutes.
    command: --interval 120 --cleanup
    restart: unless-stopped
    networks:  
      - traefik_default
    environment:
      REPO_USER: exoleverdevops
      REPO_PASS: XGe2ZgNb99XsEsYw
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: noreply@openexo.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: devops@openexo.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.sendgrid.net
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: apikey
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: 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  

networks:
  traefik_default:
    external:
      name: traefik_default
