version: '2'
services:
  traefik:
    image: traefik:v1.7
    command: >
      --accesslogsfile=/dev/stdout --logLevel=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
    environment:
      - 'GODADDY_API_KEY=dKNvuCe7LhV2_Wn4Dr1LTvRGkErBerTkLSy'
      - 'GODADDY_API_SECRET=Wn4H4aeFaKMsHdcUmH2MPK'
    networks:
      - default
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:releases.exolever.com"
      - "traefik.docker.network=traefik_default"
